Repository NREL-Sienna/PowerSystems.jl, pull requests merged in 2020-08, with the labels that each got.

#563 Add more defaults to ThermalStandard
  src/descriptors/power_system_structs.json
  src/models/generated/ThermalStandard.jl
Labels: enhancement

#565 thermal defaults
  src/descriptors/power_system_structs.json
  src/models/generated/SalientPoleMachine.jl
  src/models/generated/ThermalStandard.jl
  test/data_14bus_pu.jl
  test/data_5bus_pu.jl
  test/test_dynamic_generator.jl
Labels: enhancement

#554 Add StaticGroupReserve
  src/PowerSystems.jl
  src/base.jl
  src/descriptors/power_system_structs.json
  src/models/generated/StaticReserveGroup.jl
  src/models/generated/includes.jl
  test/test_services.jl
Labels: enhancement

#574 regulation device patch
  src/base.jl
  src/models/regulation_device.jl
Labels: bug

#580 add govs
  src/PowerSystems.jl
  src/descriptors/power_system_structs.json
  src/models/generated/GeneralGovModel.jl
  src/models/generated/HydroTurbineGov.jl
  src/models/generated/IEEETurbineGov1.jl
  src/models/generated/SteamTurbineGov1.jl
  src/models/generated/TGTypeI.jl
  src/models/generated/TGTypeII.jl
  src/models/generated/includes.jl
  src/parsers/psse_dynamic_mapping.yaml
  src/utils/conversion.jl
Labels: PARSING

#584 Include additional validations for PSS/E structs
  src/descriptors/power_system_structs.json
  src/models/generated/ESAC1A.jl
  src/models/generated/ESAC6A.jl
  src/models/generated/ESDC1A.jl
  src/models/generated/ESDC2A.jl
  src/models/generated/ESST1A.jl
  src/models/generated/ESST4B.jl
  src/models/generated/EXAC1.jl
  src/models/generated/EXAC1A.jl
  src/models/generated/EXAC2.jl
  src/models/generated/EXPIC1.jl
  src/models/generated/GasTG.jl
  src/models/generated/GeneralGovModel.jl
  src/models/generated/HydroTurbineGov.jl
  src/models/generated/IEEEST.jl
  src/models/generated/IEEET1.jl
  src/models/generated/IEEETurbineGov1.jl
  src/models/generated/SCRX.jl
  src/models/generated/SteamTurbineGov1.jl
  src/models/generated/includes.jl
Labels: PARSING

#582 Psse parse madness
  src/PowerSystems.jl
  src/descriptors/power_system_structs.json
  src/models/dynamic_generator_components.jl
  src/models/generated/AC1A.jl
  src/models/generated/AVRFixed.jl
  src/models/generated/AVRSimple.jl
  src/models/generated/AVRTypeI.jl
  src/models/generated/AVRTypeII.jl
  src/models/generated/AndersonFouadMachine.jl
  src/models/generated/AverageConverter.jl
  src/models/generated/BaseMachine.jl
  src/models/generated/Bus.jl
  src/models/generated/CurrentControl.jl
  src/models/generated/ESAC1A.jl
  src/models/generated/ESAC6A.jl
  src/models/generated/ESDC1A.jl
  src/models/generated/ESDC2A.jl
  src/models/generated/ESST1A.jl
  src/models/generated/ESST4B.jl
  src/models/generated/EXAC1.jl
  src/models/generated/EXAC1A.jl
  src/models/generated/EXAC2.jl
  src/models/generated/EXPIC1.jl
  src/models/generated/FiveMassShaft.jl
  src/models/generated/FixedDCSource.jl
  src/models/generated/FullMachine.jl
  src/models/generated/GasTG.jl
  src/models/generated/GeneralGovModel.jl
  src/models/generated/HydroTurbineGov.jl
  src/models/generated/IEEEST.jl
  src/models/generated/IEEET1.jl
  src/models/generated/IEEETurbineGov1.jl
  src/models/generated/KauraPLL.jl
  src/models/generated/LCFilter.jl
  src/models/generated/LCLFilter.jl
  src/models/generated/MarconatoMachine.jl
  src/models/generated/ModifiedAC1A.jl
  src/models/generated/OneDOneQMachine.jl
  src/models/generated/PSSFixed.jl
  src/models/generated/PSSSimple.jl
  src/models/generated/ReactivePowerDroop.jl
  src/models/generated/RoundRotorMachine.jl
  src/models/generated/SCRX.jl
  src/models/generated/ST1A.jl
  src/models/generated/SalientPoleMachine.jl
  src/models/generated/SimpleAFMachine.jl
  src/models/generated/SimpleFullMachine.jl
  src/models/generated/SimpleMarconatoMachine.jl
  src/models/generated/SingleMass.jl
  src/models/generated/SteamTurbineGov1.jl
  src/models/generated/TGFixed.jl
  src/models/generated/TGTypeI.jl
  src/models/generated/TGTypeII.jl
  src/models/generated/VirtualInertia.jl
  src/models/generated/includes.jl
  src/parsers/psse_dynamic_mapping.yaml
  src/utils/conversion.jl
  test/test_dynamic_generator.jl
  test/test_parse_dynamics.jl
Labels: PARSING

#585 Add ReserveNonSpinning
  src/PowerSystems.jl
  src/descriptors/power_system_structs.json
  src/models/generated/StaticReserveNonSpinning.jl
  src/models/generated/VariableReserve.jl
  src/models/generated/VariableReserveNonSpinning.jl
  src/models/generated/includes.jl
  src/models/reserves.jl
  test/test_services.jl
Labels: enhancement

#591 change errors to warn
  src/descriptors/power_system_structs.json
  src/models/generated/Line.jl
  src/models/generated/MonitoredLine.jl
  src/models/generated/PhaseShiftingTransformer.jl
  src/models/generated/TapTransformer.jl
  src/models/generated/Transformer2W.jl
Labels: bug

#592 add missing exports
  src/PowerSystems.jl
Labels: enhancement

#593 Simplify System constructor
  src/base.jl
  test/common.jl
  test/test_busnumberchecks.jl
  test/test_devices.jl
  test/test_network_matrices.jl
  test/test_powerflow.jl
  test/test_powersystemconstructors.jl
  test/test_validation.jl
Labels: breaking

#595 Added struct for Zero Order Battery Model (ZeroOrderBESS.jl)
  src/PowerSystems.jl
  src/descriptors/power_system_structs.json
  src/models/generated/ZeroOrderBESS.jl
  src/models/generated/includes.jl
  test/test_dynamic_inverter.jl
Labels: enhancement

#596 cost function updates
  src/descriptors/power_system_structs.json
  src/models/generated/MarketBidCost.jl
  src/models/generated/MultiStartCost.jl
  src/models/generated/ThermalMultiStart.jl
  src/models/generated/ThreePartCost.jl
  src/models/generated/includes.jl
  src/parsers/power_models_data.jl
Labels: breaking, enhancement

#597 adding PHES
  src/PowerSystems.jl
  src/descriptors/power_system_structs.json
  src/models/generated/HydroPumpedStorage.jl
  src/models/generated/includes.jl
  src/parsers/power_system_table_data.jl
  test/test_printing.jl
  test/test_serialization.jl
  test/test_validation.jl
Labels: enhancement
