Repository NREL-Sienna/PowerSystems.jl, pull requests merged in 2020-10, with the labels that each got.

#602 add Hybrid System
  docs/make.jl
  docs/src/model_library/hybrid_device.md
  src/PowerSystems.jl
  src/models/HybridSystem.jl
  test/test_hybrid_system.jl
Labels: enhancement

#627 Time series docs
  docs/src/user_guide/time_series.md
Labels: documentation

#638 Add dynamics documentation
  Project.toml
  docs/make.jl
  docs/src/modeler_guide/example_dynamic_data.md
  docs/src/modeler_guide/parsing.md
  docs/src/modeler_guide/system_dynamic_data.md
Labels: documentation

#637 Adding documentation for MarketBidCost
  docs/src/model_developer/market_bid_cost.md
  src/models/cost_function_timeseries.jl
Labels: documentation

#639 add base_power setting
  src/base.jl
  src/models/dynamic_generator.jl
  src/models/dynamic_inverter.jl
  test/test_dynamic_generator.jl
Labels: bug

#640 add convert methods for enums
  src/models/serialization.jl
  src/parsers/common.jl
  src/parsers/enums.jl
  src/parsers/power_models_data.jl
  src/parsers/power_system_table_data.jl
Labels: PARSING
