Repository NREL-Sienna/PowerSystems.jl, pull requests merged in 2021-01, with the labels that each got.

#692 Replace all enums with new scoped_enum macro
  src/definitions.jl
  src/descriptors/power_system_structs.json
  src/models/components.jl
  src/models/generated/AVRFixed.jl
  src/models/generated/AVRSimple.jl
  src/models/generated/AVRTypeI.jl
  src/models/generated/AVRTypeII.jl
  src/models/generated/Bus.jl
  src/models/generated/ESAC1A.jl
  src/models/generated/ESAC6A.jl
  src/models/generated/ESDC1A.jl
  src/models/generated/ESDC2A.jl
  src/models/generated/ESST1A.jl
  src/models/generated/ESST4B.jl
  src/models/generated/EXAC1.jl
  src/models/generated/EXAC1A.jl
  src/models/generated/EXAC2.jl
  src/models/generated/EXPIC1.jl
  src/models/generated/GasTG.jl
  src/models/generated/GeneralGovModel.jl
  src/models/generated/GenericBattery.jl
  src/models/generated/HydroDispatch.jl
  src/models/generated/HydroEnergyReservoir.jl
  src/models/generated/HydroPumpedStorage.jl
  src/models/generated/HydroTurbineGov.jl
  src/models/generated/IEEEST.jl
  src/models/generated/IEEET1.jl
  src/models/generated/IEEETurbineGov1.jl
  src/models/generated/InterruptibleLoad.jl
  src/models/generated/PowerLoad.jl
  src/models/generated/RenewableDispatch.jl
  src/models/generated/RenewableFix.jl
  src/models/generated/SCRX.jl
  src/models/generated/SteamTurbineGov1.jl
  src/models/generated/ThermalMultiStart.jl
  src/models/generated/ThermalStandard.jl
  src/models/supplemental_constructors.jl
  src/parsers/common.jl
  src/parsers/enums.jl
  src/parsers/pm_io/common.jl
  src/parsers/power_models_data.jl
  src/parsers/power_system_table_data.jl
Labels: breaking

#685 Adding new field to GenericBattery
  src/PowerSystems.jl
  src/descriptors/power_system_structs.json
  src/models/generated/BatteryEMS.jl
  src/models/generated/includes.jl
Labels: enhancement

#694 fix enum implementation
  src/descriptors/power_system_structs.json
  src/models/generated/BatteryEMS.jl
Labels: bug

#696 minor pm parser_updates
  src/base.jl
  src/parsers/TAMU_data.jl
  src/parsers/pm_io/common.jl
  src/parsers/power_models_data.jl
Labels: PARSING, enhancement

#698 Fix handling of System kwargs in deserialize
  src/base.jl
Labels: bug

#699 bus number serialization
  src/base.jl
  test/common.jl
Labels: bug
