Repository NREL-Sienna/PowerSystems.jl, pull requests merged in 2021-06, with the labels that each got.

#757 add Grid Following structs
  src/PowerSystems.jl
  src/descriptors/power_system_structs.json
  src/models/generated/ActivePowerPI.jl
  src/models/generated/CurrentControl.jl
  src/models/generated/CurrentModeControl.jl
  src/models/generated/ReactivePowerPI.jl
  src/models/generated/ReducedOrderPLL.jl
  src/models/generated/VoltageModeControl.jl
  src/models/generated/includes.jl
  test/test_dynamic_inverter.jl
  test/test_powersystemconstructors.jl
Labels: enhancement

#761 deprecate current control in favor of voltagemodecontrol
  docs/src/modeler_guide/system_dynamic_data.md
  src/deprecated.jl
  src/descriptors/power_system_structs.json
  src/models/generated/CurrentControl.jl
  src/models/generated/includes.jl
  test/common.jl
  test/test_deprecations.jl
  test/test_dynamic_inverter.jl
Labels: enhancement

#765 fix rating calculation
  src/parsers/power_models_data.jl
Labels: PARSING, bug

#764 Optimize deepcopy of System
  src/base.jl
  test/test_system.jl
Labels: bug

#768 add V_ref to SEXS struct
  src/descriptors/power_system_structs.json
  src/models/generated/SEXS.jl
Labels: bug

#771 add convert to area power fields
  src/descriptors/power_system_structs.json
  src/models/generated/Area.jl
  src/models/generated/LoadZone.jl
Labels: enhancement

#770 Add SEXS parser
  src/parsers/psse_dynamic_mapping.yaml
  test/test_parse_dynamics.jl
Labels: PARSING, enhancement

#772 remove conversion
  src/utils/power_flow.jl
Labels: bug

#773 Add white background to gen_metamodel figure
  docs/src/assets/gen_metamodel.png
Labels: documentation

#774 Compare values
  docs/src/modeler_guide/system.md
  src/PowerSystems.jl
  src/base.jl
  test/common.jl
  test/test_power_system_table_data.jl
  test/test_serialization.jl
  test/test_system.jl
Labels: enhancement
