Repository NREL-Sienna/PowerSystems.jl, pull requests merged in 2021-09, with the labels that each got.

#795 Add Parser for Generic Renewable Models
  src/models/dynamic_inverter.jl
  src/parsers/psse_dynamic_data.jl
  src/parsers/psse_dynamic_mapping.yaml
  test/test_parse_dynamics.jl
Labels: PARSING

#798 get time series counts bugfix
  src/base.jl
  test/test_system.jl
Labels: bug

#809 merge doc patch prs
  README.md
  docs/src/index.md
  docs/src/modeler_guide/network_matrices.jl
  docs/src/modeler_guide/system.md
  docs/src/modeler_guide/time_series.md
  docs/src/modeler_guide/type_structure.md
  docs/src/tutorials/intro_page.md
Labels: documentation

#813 Fix time_periods in Modeling with JuMP
  docs/src/modeler_guide/modeling_with_JuMP.jl
Labels: documentation

#810 Cb/update pm parsers
  src/parsers/im_io/matlab.jl
  src/parsers/pm_io/matpower.jl
  src/parsers/power_models_data.jl
Labels: bug, PARSING
