Repository NREL-Sienna/PowerSystems.jl, pull requests merged in 2025-08, with the labels that each got.

#1499 Sign convention for constant admittance to build zip loads
  src/parsers/pm_io/psse.jl
  test/test_parse_psse.jl
Labels: PARSING

#1518 add new abstract typo "UnplannedOutage" for GeometricDistributionForcedOutage and FixedForcedOutage.
  src/outages.jl
Labels: enhancement, PowerSystems 5.0

#1517 add turbine enum
  src/definitions.jl
  src/descriptors/power_system_structs.json
  src/models/generated/HydroDispatch.jl
  src/models/generated/HydroPumpTurbine.jl
  src/models/generated/HydroTurbine.jl
  src/models/generated/SynchronousCondenser.jl
  src/models/generated/includes.jl
Labels: PowerSystems 5.0

#1519 fix enum docstrings
  src/PowerSystems.jl
  src/definitions.jl
Labels: PowerSystems 5.0
