Repository NREL-Sienna/PowerSystems.jl, pull requests merged in 2025-04, with the labels that each got.

#1315 add new struct for switch/breaker
  src/definitions.jl
  src/descriptors/power_system_structs.json
  src/models/generated/DiscreteControlledACBranch.jl
  src/models/generated/includes.jl
Labels: PowerSystems 5.0

#1331 Update cross-package-test.yml
  .github/workflows/cross-package-test.yml
Labels: tests

#1332 change type of DynamicBranch from ACBranch to ACTransmission; fix namespace collision for nodes5(), nodes14() in tests
  src/models/dynamic_branch.jl
  test/data_14bus_pu.jl
  test/data_5bus_pu.jl
  test/runtests.jl
  test/test_powersystemconstructors.jl
  test/test_readnetworkdata.jl
  test/test_validation.jl
Labels: code bug, PowerSystems 5.0, tests

#1307 feat(hydro): Adding new Hydro structs for `HydroPowerSimulations`
  .pre-commit-config.yaml
  docs/src/model_library/hydro_reservoir.md
  src/PowerSystems.jl
  src/base.jl
  src/definitions.jl
  src/descriptors/power_system_structs.json
  src/models/HydroReservoir.jl
  src/models/devices.jl
  src/models/generated/HydroTurbine.jl
  src/models/generated/includes.jl
  src/parsers/enums.jl
  test/test_constructors.jl
  test/test_hydro_reservoir.jl
Labels: PowerSystems 5.0

#1298 Shiftable power load
  Project.toml
  src/PowerSystems.jl
  src/descriptors/power_system_structs.json
  src/models/generated/ShiftablePowerLoad.jl
  src/models/generated/includes.jl
  test/data_5bus_pu.jl
  test/test_constructors.jl
  test/test_powersystemconstructors.jl
Labels: NewStruct
